#! /usr/bin/env bash

set -e

source script/env "$@"

echo "[-] Killing old docker processes"
docker compose -f docker-compose.yml down --remove-orphans -v -t 1

echo "[i] Building docker containers"
docker compose run --rm server create_db
docker compose -f docker-compose.yml up --build -d

echo -e "[+] Containers are now running!"
